// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9qlMNe2VNfyrC_SS3iotTUabGD8BvUCI',
    appId: '1:347844520434:web:a94a5840a3cfac8dfea36b',
    messagingSenderId: '347844520434',
    projectId: 'my-bolt-ai',
    authDomain: 'my-bolt-ai.firebaseapp.com',
    storageBucket: 'my-bolt-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKQat6RMckPGMqcPoXr-efoXFZf4CIt3I',
    appId: '1:347844520434:android:9684c3d5bfca2b18fea36b',
    messagingSenderId: '347844520434',
    projectId: 'my-bolt-ai',
    storageBucket: 'my-bolt-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGFKm_1BrSKxeaEd6O0ouFpHM3fOwF0CM',
    appId: '1:347844520434:ios:abed7a21723a552bfea36b',
    messagingSenderId: '347844520434',
    projectId: 'my-bolt-ai',
    storageBucket: 'my-bolt-ai.firebasestorage.app',
    iosBundleId: 'com.example.aiChatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGFKm_1BrSKxeaEd6O0ouFpHM3fOwF0CM',
    appId: '1:347844520434:ios:abed7a21723a552bfea36b',
    messagingSenderId: '347844520434',
    projectId: 'my-bolt-ai',
    storageBucket: 'my-bolt-ai.firebasestorage.app',
    iosBundleId: 'com.example.aiChatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9qlMNe2VNfyrC_SS3iotTUabGD8BvUCI',
    appId: '1:347844520434:web:9c686aea105d04cffea36b',
    messagingSenderId: '347844520434',
    projectId: 'my-bolt-ai',
    authDomain: 'my-bolt-ai.firebaseapp.com',
    storageBucket: 'my-bolt-ai.firebasestorage.app',
  );
}
